apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalDynamicSecret
metadata:
  name: infisicaldynamicsecret
spec:
  hostAPI: https://app.infisical.com/api # Optional, defaults to https://app.infisical.com/api
  dynamicSecret:
    secretName: dynamic-secret-lease
    projectSlug: <Add Project Slug Here>
    secretsPath: /  #Root
    environmentSlug: prod
  leaseRevocationPolicy: Revoke
  leaseTTL: 1m
  managedSecretReference:
    secretName: dynamic-secret-test
    secretNamespace: default # Must be the same namespace as the InfisicalDynamicSecret CRD.
    creationPolicy: Orphan
  authentication:
    kubernetesAuth:
      identityId: <Add Machine Identity ID Here>
      serviceAccountRef:
        name: infisical-service-account
        namespace: default
