apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: infisical-push-secret-demo
spec:
  resyncInterval: 1m # Remove this field to disable automatic reconciliation of the InfisicalPushSecret CRD.
  hostAPI: https://app.infisical.com/api
  updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.
  deletionPolicy: Delete # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted
  destination:
    projectSlug: <Add Project Slug Here>
    environmentSlug: prod
    secretsPath: /

  push:
    secret:
      secretName: push-secret-demo #pull from source-secret.yaml
      secretNamespace: default
  authentication:
    kubernetesAuth:
      identityId: <Add Machine Identity ID Here>  
      serviceAccountRef:
        name: infisical-service-account
        namespace: default
