apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-sample-crd
spec:
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: <Add Machine Identity ID Here>
      serviceAccountRef:
        name: infisical-service-account
        namespace: default
      secretsScope:
        envSlug: prod
        projectSlug: <Add Project Slug Here>
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: managed-secret
      secretNamespace: default
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          SMTP: "{{ .SMTP_HOST.SecretPath }} {{ .SMTP_HOST.Value }}"
