apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: infisical-service-account-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "infisical-service-account"
